services:
  - type: web
    name: calorie-backend
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calorie-tracker-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

databases:
  - name: calorie-db
    region: oregon
    plan: free